/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectokohlercarlos;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TecaFondo
 */
public class Menu extends javax.swing.JFrame{
    private ArrayList<Usuario> usrs= new ArrayList<>();

    /**
     * Creates new form Menu
     */
    public Menu() throws SQLException{
        this.cn = cc.conexion();
        initComponents();
        guardarDatos("");
    }
    public Menu(ArrayList<Usuario> usrs) throws SQLException{
        this.cn=cc.conexion();
        initComponents();
        if(this.usrs.size()<usrs.size()){
            for(int i=this.usrs.size();i<usrs.size();i++){
                this.usrs.add(usrs.get(i));
                cargarDatos(usrs.get(i)); //Se cargan usuarios nuevos a la base de datos
            }
        }
        if(this.usrs.size()==usrs.size()){ //Actualiza los cambios realizados a la base de datos
            this.usrs=usrs;
            for(int i=0;i<this.usrs.size();i++){
                try{
                    String query = "DELETE FROM usuarios WHERE nombre = ?";
                    PreparedStatement pst = cn.prepareStatement(query);
                    pst.setString(1,this.usrs.get(i).getUsr());
                    pst.executeUpdate();
                }
                catch (SQLException e){
                    System.out.println("a"+e);
                }
            }
            for(int i=0;i<this.usrs.size();i++){
                cargarDatos(this.usrs.get(i));
            }
        }
        
        
    }
    void guardarDatos(String valor) throws SQLException{// Metodo mostrardatos
        
        String sql="";
        if (valor.equals("")){
            sql="SELECT * FROM usuarios";
        }
        else{
            System.out.println(valor);
            sql="SELECT * FROM usuarios WHERE Nombre='"+valor+"'";
        }
        
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){ //se incorporan los usuarios de la base de datos a un array list local para trabajo dentro de app.
                this.usrs.add(new Usuario(rs.getString(1),rs.getString(2)));
                //System.out.println(usrs.get(0).getUsr()); // impresion para ver action performed
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(EasyKeyGUI.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("");
        }
        
    }
    
    void cargarDatos(Usuario usr) throws SQLException{
        try{ //carga de datos a la base de datos
                PreparedStatement pst = cn.prepareStatement("INSERT INTO usuarios (Nombre, Clave) VALUES (?,?)"); //estructura de carga
                pst.setString(1, usr.getUsr());
                pst.setString(2, usr.getPwd());
                pst.execute();
                pst.executeUpdate();
                }
            catch (Exception e){
                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLogo = new javax.swing.JLabel();
        jCopciones = new javax.swing.JComboBox<>();
        jBir = new javax.swing.JButton();
        jBsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectokohlercarlos/easyKeyLogo.jpg"))); // NOI18N

        jCopciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Login", "Nuevo Usuario", "Cambiar Contraseña" }));
        jCopciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCopcionesActionPerformed(evt);
            }
        });

        jBir.setText("IR");
        jBir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBirActionPerformed(evt);
            }
        });

        jBsalir.setText("EXIT");
        jBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBsalir)
                            .addComponent(jBir)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jCopciones, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jCopciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCopcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCopcionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCopcionesActionPerformed

    private void jBirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBirActionPerformed
        // TODO add your handling code here:
        if( jCopciones.getSelectedItem().equals("Login") ){
            new EasyLogGUI(this.usrs).setVisible(true);
            dispose();
        }
        else if(jCopciones.getSelectedItem().equals("Nuevo Usuario")){
            new NewUsr(this.usrs).setVisible(true);
            dispose();
        }
        else if(jCopciones.getSelectedItem().equals("Cambiar Contraseña")){
            new NewPw(this.usrs).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jBirActionPerformed

    private void jBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Menu().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBir;
    private javax.swing.JButton jBsalir;
    private javax.swing.JComboBox<String> jCopciones;
    private javax.swing.JLabel jLogo;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    conectar cc = new conectar();
    Connection cn;
}
